//TODO: USING SUFFIXES IN INTEGER LITERAL.....
#include<iostream>
using namespace std;
int main()
{
    int a = 124;
    unsigned int b = 124U; //***!here ["U"] is unsigned...
    long int c = 124L; //***!here ["L"] is long...
    long long int d = 124LL; //***!here ["LL"] IS LONG LONG...
    cout << a << " " << b << " "<< c <<" "<< d;
    return 0;
}