//!..Pointers Basic....
#include<iostream>
using namespace std;
int main() {
    int x  = 10;
    int *p;  //store memory address
    p = &x; //!.P will store memeory address of P...
    cout<< x <<endl; //normal value of x i.e 10 will print...
    cout<< *p <<endl; //store memory address of means value at that address will print...
    cout<< p <<endl; //Print memory address.. 

//!..Memory addres can differ from machine to machine...
}