#include<iostream>
using namespace std;
int main() {
    int x=10;
    int *ptr = &x; //!ptr will hold the value stored at the address of x...
    cout<<*ptr<<endl; //print the value at the address of x...
    x = x + 30;
    cout<<*ptr<<endl; //print the modified value of the address of x...
    *ptr = *ptr + 40;
    cout<<x<<endl; //print the modified value saved at the address of x...
}